<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.0.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario Inscríbete',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => 'contacto@viannainmexico.com',
		'to' => 'contacto@viannainmexico.com'
	),
	'fields' => array(
		'custom_U1025' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Primeiro Nome',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Primeiro Nome\' es obligatorio.'
			)
		),
		'Email' => array(
			'order' => 5,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Email\' es obligatorio.',
				'format' => 'El campo \'Email\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U1041' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Último Nome',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Último Nome\' es obligatorio.'
			)
		),
		'custom_U1045' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Nome para o Crachá',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nome para o Crachá\' es obligatorio.'
			)
		),
		'custom_U1049' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Data de Nascimento',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Data de Nascimento\' es obligatorio.'
			)
		),
		'custom_U1053' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Telefone',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Telefone\' es obligatorio.'
			)
		),
		'custom_U1057' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Contato de Emergência (nome e telefone)
 number)',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Contato de Emergência (nome e telefone)
 number)\' es obligatorio.'
			)
		),
		'custom_U1061' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Endereço',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Endereço\' es obligatorio.'
			)
		),
		'custom_U1065' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'País de residência',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'País de residência\' es obligatorio.'
			)
		),
		'custom_U1069' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Seminários que está interesado(a)',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Seminários que está interesado(a)\' es obligatorio.'
			)
		),
		'custom_U1073' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Quem convidou para o seminário',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Quem convidou para o seminário\' es obligatorio.'
			)
		),
		'custom_U1077' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Necessita tradução?',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Necessita tradução?\' es obligatorio.'
			)
		),
		'custom_U1081' => array(
			'order' => 10,
			'type' => 'checkbox',
			'label' => 'Tenho mais de 18 anos e tenho total responsabilidade por minha participação neste(s) seminario(s)',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Tenho mais de 18 anos e tenho total responsabilidade por minha participação neste(s) seminario(s)\' es obligatorio.'
			)
		),
		'custom_U1104' => array(
			'order' => 13,
			'type' => 'checkbox',
			'label' => 'Sei e concordo com as políticas de cancelamento',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Sei e concordo com as políticas de cancelamento\' es obligatorio.'
			)
		)
	)
);

process_form($form);
?>
